# Generated by Django 3.1.3 on 2021-01-05 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoApro', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Aprobaciones',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descDepartamento', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codEmpleado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.departamento')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('codEquipo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcionEqui', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descEstado', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='EstadoRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descRep', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Estado de reparción',
            },
        ),
        migrations.CreateModel(
            name='FamiliaVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionFamilia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Familia de vehículos',
            },
        ),
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('codJefe', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Jefes',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('codOrdenTrab', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descOrden', models.CharField(max_length=50, null=True)),
                ('codEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.equipo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.estado')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de trabajo',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descPuesto', models.CharField(default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Usuario')),
                ('password', models.CharField(max_length=30, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripActi', models.CharField(max_length=50, verbose_name='Descripción de la actividad')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('horaIni', models.TimeField(auto_now_add=True, verbose_name='Hora de inicio')),
                ('horaFin', models.TimeField(verbose_name='Hora de finalización')),
                ('codequipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.equipo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.empleado')),
                ('estadoApro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.aprobacion')),
                ('estadoReparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.estadorep')),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.jefe')),
                ('ordenTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.ordentrabajo')),
            ],
            options={
                'verbose_name_plural': 'Reparaciones',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='codFamilia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.familiavehiculo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='descPuesto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_forms.puesto'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='jefe',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app_forms.jefe'),
        ),
    ]
