# Generated by Django 3.1.5 on 2021-03-03 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='codEmpleado',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='jefe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_forms.jefe'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codEquipo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código de Equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcionEqui',
            field=models.CharField(max_length=50, verbose_name='Descripción de Equipo'),
        ),
        migrations.AlterField(
            model_name='jefe',
            name='codJefe',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='codOrdenTrab',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código Orden de Trabajo'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descOrden',
            field=models.CharField(max_length=50, null=True, verbose_name='Descripción'),
        ),
    ]
