# Generated by Django 3.1.5 on 2021-03-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0006_auto_20210308_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='codEquipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_forms.equipo'),
        ),
    ]
