# Generated by Django 3.1.5 on 2021-03-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0007_auto_20210309_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codFamilia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_forms.familiavehiculo'),
        ),
    ]
