# Generated by Django 3.1.5 on 2021-03-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0008_auto_20210309_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='descPuesto',
        ),
        migrations.AlterField(
            model_name='familiavehiculo',
            name='descripcionFamilia',
            field=models.CharField(max_length=50, verbose_name='Descripción familia'),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Puesto',
        ),
    ]
