# Generated by Django 3.1.5 on 2021-03-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms', '0009_auto_20210309_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='jefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_forms.jefe'),
        ),
    ]
